language: android
jdk: oraclejdk8

env:
  # Global variables for convenience
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - ANDROID_ABI=armeabi-v7a

# Disable travis email notifs
notifications:
  email: false

# Execute before install
before_install:
  # Install the android and build tools and accept the license
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

# Components necessary for building android project
android:
  components:
    - tools
    - platform-tools
    - extra
    #    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    #    - android-$ANDROID_API_LEVEL

# Execute scripts before
before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean assemble

# NOTE: build does assemble and testing and linting
#  - ./gradlew clean build
