name: Android CI
on: [pull_request, push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build the app/gradle
        run: ./gradlew build

      - name: Run android lint
        run: ./gradlew lint

      - name: Run app on an emulator
        uses: ReactiveCircus/android-emulator-runner@v2.12.0
        with:
          api-level: 29
          arch: x86
          script: ./gradlew connectedCheck jacocoTestReport createDebugCoverageReport

      - name: Codecov
        uses: codecov/codecov-action@v1.0.13

      - name: Set up JDK 11 for SonarQube analysis
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR info
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
