name: reviewdog
on: [pull_request, push]

jobs:
  reviewdog-github-check:
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build the app and generate lint
        run: ./gradlew build

      - name: Run reviewdog analysis
        uses: dvdandroid/action-android-lint@v1.1
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          level: warning # info, warning, error are the possible values
          reporter: github-check # github-check, github-pr-check, github-pr-review are possible values
          lint_xml_file: app/build/reports/lint-results.xml
